### ISSUE TITLE
dokuwiki formatting support

### ISSUE THREAD

**Issue by LadyR123** [hanche/dokuwiki_color_plugin#1]
Hello!
Can you fix please this parsing:
<color #ed1c24>=====v1.3:=====</ color >
It have to be red header

**Comment by hanche** [comment]
The color plugin works by creating a `<span>` element with the desired colour(s). As you should not wrap a `<span>` around a block level element like a header, this is not feasible. Better would be to allow the setting of colour *within* the header, but AFAIK, dokuwiki doesn't let you apply any sort of formatting within a header.

In short, achieving coloured headers seems to be beyond the possibilities for the color plugin.

I am on vacation now, and will not spend time investigating the possibilities further until I am back. I may take another look, but most likely I will end up not fixing it.

If you can find a clean and simple solution, I will of course consider a pull request.

**Comment by hanche** [comment]
Here is a [FAQ entry](https://www.dokuwiki.org/faq:headerlinks) explaining that formatting can't be applied inside headers.

Also, see issue #2 for an explanation why you can't wrap `<color>` *around* a header (which might otherwise be a reasonable workaround).
