### ISSUE TITLE
warning with php 7.3 and Hogfather RC

### ISSUE THREAD

**Issue by arlt** [hanche/dokuwiki_color_plugin#3]
```
PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_UNMATCHED - assumed 'DOKU_LEXER_UNMATCHED' (this will throw an Error in a future version of PHP) in /var/www/dokuwiki/lib/plugins/color/syntax.php on line 87
```

**Comment by hanche** [comment]
Hmm, this seems like it could potentially be a problem with dokuwiki itself. I am going to sit out the discussion on the  corresponding [columns issue](https://github.com/dwp-forge/columns/issues/5#issuecomment-638069776) and see if a solution will emerge from that.

**Comment by hanche** [comment]
The pull request (for dokuwiki) shown above will likely resolve this issue. However, I am keeping it open for a while longer in case not.

**Comment by hanche** [comment]
@arlt There is some reason to hope that Hogfather RC3 made this problem go away. Could you try it and find out?

**Comment by arlt** [comment]
@splitbrain @hanche fixed with RC3
