### ISSUE TITLE
syntax.php is deprecated

### ISSUE THREAD

**Issue by fiwswe** [hanche/dokuwiki_color_plugin#5]
…/data/log/deprecated/*.log shows entries such as this:
`2022-09-06 13:28:11		syntax.php is deprecated. It was called from require_once() in /dokuwiki-test/lib/plugins/syntax.php:3 Do not require() files yourself. Autoloading should be used instead!`

A grep over the plugins folder turned up this which I suspect is one of the causes of the message:
`/var/www/dokuwiki-test/lib/plugins/color/syntax.php:require_once(DOKU_PLUGIN.'syntax.php');`
See: https://github.com/hanche/dokuwiki_color_plugin/blob/master/syntax.php#L13

Commenting the line seems to solve the issue.

fiwswe

**Comment by hanche** [comment]
Indeed, this practice was deprecated long ago, almost since the color plugin was born, years before I took over.
