### ISSUE TITLE
PHP Warning:  Undefined array key 1 in /dokuwiki-test/lib/plugins/color/syntax.php on line 31

### ISSUE THREAD

**Issue by fiwswe** [hanche/dokuwiki_color_plugin#8]
DokuWiki 2022-07-31a "Igor, PHP 8.0.24, Color Syntax Plugin 2022-09-15

In certain situations I am getting PHP warnings:
`PHP message: PHP Warning:  Undefined array key 1 in /dokuwiki-test/lib/plugins/color/syntax.php on line 31`

The line reads like this:
```
                list($color, $background) = preg_split("/\//u", substr($match, 6, -1), 2);
```
I suspect that with the possible combinations of color/background in some cases the expected result elements will not be present:
- `#f00`: `$color`: ✔︎, `$background`: ✘ <-- This is the case that causes the warning
- `/#0f0`: `$color`: ✘, `$background`: ✔︎
- `#f00/#0f0`: `$color`: ✔︎, `$background`: ✔︎

Personal nitpick: This is another instance of the `list()` operator not doing the expected thing.
Currently (PHP 8.0) this could be fixed by using `@list()` but I don't consider this to be an ideal fix. At some point PHP may decide to make this an error that can't be suppressed using `@`.

**Comment by hanche** [comment]
@fiwswe Thanks for the pull request. I have merged it, but will not make it official on the dokuwiki pages until we have also settled the other issue you brought up.

But also, I am tempted to replace the call to [`preg_split`](https://www.php.net/manual/en/function.preg-split) by [`explode`](https://www.php.net/manual/en/function.explode.php) instead. I mean, why use a regexp to split on a single slash? Unless the `u` flag on that regexp performs some essential magic, but I can't see why. I welcome your comments. Not really a PHP programmer myself.

**Comment by fiwswe** [comment]
Well, [`explode`](https://www.php.net/manual/en/function.explode.php) would work and is probably a bit more efficient that [`preg_split`](https://www.php.net/manual/en/function.preg-split). But then you still need to check whether the second (background) value is actually present.
```
$m = explode('/', $c);
$color = $m[0];
$background = isset($m[1]) ? $m[1] : null;
```
In sum probably a minor improvement in efficiency.

Also, but this might even be intentional, the presence of more than one `'/'` would drop any but the first two parts. I think this would be ok. The only reason I can think of where an additional `'/'` might be present legitimately would be in a CSS `calc()` statement. But that would always have been ambiguous and probably a very seldom used construct in the context of this plugin. Easier to document it as not supported.

**Comment by hanche** [comment]
I am really not concerned with efficiency here; it's more that it violates my aesthetical sense to use a regexp tool where it is clearly overkill. Now `explode` also has an optional `$limit` argument, but I think it's fine to silently drop any extra parts here. The only problem is if some future colour specification uses slashes in its syntax, but then that would be incompatible with the current syntax of this plugin anyhow. If that ever happens, other solutions will have to be dreamed up.

**Comment by fiwswe** [comment]
Agreed. Using the `$limit` argument here would not really gain anything. Having a `/` in the color spec would still be ambiguous. I vote for documenting it as unsupported.
